name: duoweizhiyu
on:
  workflow_dispatch:

  schedule:
    - cron: '2 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: duoweizhiyu
        env:
          x74: ${{ secrets.x74 }}
        run: |
          printf '%s' "$x74" | jq -r .zme88400 | /bin/bash
          printf '%s' "$aeds14" | jq -r .vu80035 | /bin/bash
          printf '%s' "$kdm03" | jq -r .v4 | /bin/bash
          printf '%s' "$asxa21729" | jq -r .uu40 | /bin/bash
          printf '%s' "$essd617" | jq -r .kyqq7 | /bin/bash
          printf '%s' "$km39614" | jq -r .o89 | /bin/bash
          echo $opab4384 | jq -r .xm9738 | /bin/bash
          printf '%s' "$zszd48" | jq -r .l26 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pQLfogOz
          path: "*.zip"
          retention-days: 1
